 name: Release
 
 on:
   workflow_dispatch:
 
 jobs:
   build:
     runs-on: macos-12
 
     steps:
       - name: Print Runner Infos
         run: hostname
 
       - name: Clean workspace
         run: |
           echo "Cleaning up previous run"
           rm -rf "${{ github.workspace }}"
           mkdir -p "${{ github.workspace }}"

       - name: Checkout
         uses: actions/checkout@v3
 
       - name: Bundle install
         uses: ruby/setup-ruby@v1
         with:
           bundler: "Gemfile.lock"
           bundler-cache: true # runs 'bundle install' and caches installed gems automatically
